server:
  port: 8181

spring:
  application:
    name: logfile-analyzer
  profiles:
    active: dev

project:
  name: Log File Analyzer
  version: 0.0.1-SNAPSHOT
  description: Parses log files, analyzes user activity, and exposes results via REST or CLI

logging:
  level:
    root: INFO
    za.co.frei.logfile.analyzer: DEBUG

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
  show-actuator: false