server:
  port: 8181
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: logfile-analyzer
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
      file-size-threshold: 2KB

project:
  name: Log File Analyzer
  version: 0.0.1-SNAPSHOT
  description: Parses log files, analyzes user activity, and exposes results via REST or CLI

logging:
  level:
    root: INFO
    za.co.frei.logfile.analyzer: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/logfile-analyzer.log
    max-size: 10MB
    max-history: 7

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true
  show-actuator: false